/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/sword2.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh 
        geometry={nodes.low005.geometry} 
        material={materials['sword.001']} 
        position={[-1.0, 0, 2]} 
        rotation={[0, 1, 0]}
      />
    </group>
  )
}

useGLTF.preload('/sword2.glb')
